# Generated by Django 5.2.15 on 2026-06-09 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_ride_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='captains/')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('driving_license', models.CharField(max_length=50, unique=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Verification')], default='pending_verification', max_length=30)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('customer', 'Customer'), ('captain', 'Captain')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rapido.captain')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rapido.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_type', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('cab', 'Cab Economy')], default='bike', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('captain_assigned', 'Captain Assigned'), ('captain_arrived', 'Captain Arrived'), ('ride_started', 'Ride Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_address', models.TextField()),
                ('drop_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('estimated_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wallet', 'Wallet'), ('upi', 'UPI'), ('card', 'Card')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='rapido.captain')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='rapido.customer')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='rapido.promocode')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RideCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_by', models.CharField(choices=[('customer', 'Customer'), ('captain', 'Captain'), ('system', 'System')], max_length=10)),
                ('reason', models.CharField(choices=[('driver_not_arriving', 'Driver Not Arriving'), ('wrong_location', 'Wrong Location'), ('change_of_plans', 'Change of Plans'), ('high_fare', 'High Fare'), ('others', 'Others')], default='others', max_length=30)),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('penalty_charged', models.BooleanField(default=False)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cancelled_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='rapido.ride')),
            ],
            options={
                'ordering': ['-cancelled_at'],
            },
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_by_customer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_by_captain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review_by_customer', models.TextField(blank=True, null=True)),
                ('review_by_captain', models.TextField(blank=True, null=True)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional tip given by customer to captain after the ride', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='rapido.ride')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('refund', 'Refund')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='rapido.customer')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapido.ride')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
